# Site settings
title: Interesting
subtitle: Very interesting
email: luka.horvat9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A programming blog dedicated to everything I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lukahorvat.github.io" # the base hostname & protocol for your site
github_username: LukaHorvat

# Build settings
markdown: kramdown
permalink: pretty