fsharp-drawer:
    name: Bezier
    description: "A small drawing library written in F# used to draw Bezier curves in an interesting way"
compose:
    name: Compose
    description: "A component based game library for Haskell"
hash:
    name: Hash
    description: "A simple bash-like language written in Haskell"
interface:
    name: Interface
    description: "OO-style interfaces for Haskell"
status-bar:
    name: StatusBar
    description: "A desktop status bar."
haskellforms:
    name: "HaskellForms"
    description: "WinForms bindings for Haskell"
